import type { CountryFeature, CountryGeometryData, CountryProperties } from "@/types/geo";

// ==========================================
// Prebuilt country data loader
// ==========================================
//
// public/data/countries.{json,bin} are generated by `pnpm geometry`
// (scripts/build-geometry.mjs). Triangulation, hole handling and curvature
// subdivision all happen at build time; the browser only decodes buffers.

const FORMAT_VERSION = 1;

interface Section {
  byteOffset: number;
  length: number;
}

interface CountryRecord {
  properties: CountryProperties;
  label: [number, number];
  vertexCount: number;
  indexCount: number;
  borderSegments: number;
}

interface CountryManifest {
  version: number;
  layout: Record<"fillLonLat" | "fillIndex" | "borderLonLat", Section>;
  countries: CountryRecord[];
}

export interface CountryData {
  countries: CountryFeature[];
  geometry: CountryGeometryData;
}

/**
 * Inverse of the build script's zigzag delta encoding (16-bit wrap-around).
 * `stride` interleaved channels are decoded independently.
 */
function deltaDecode16(encoded: Uint16Array, stride: number): Uint16Array {
  const out = new Uint16Array(encoded.length);
  const prev = new Uint16Array(stride);
  for (let i = 0; i < encoded.length; i++) {
    const channel = i % stride;
    const zz = encoded[i];
    const delta = (zz >>> 1) ^ -(zz & 1);
    prev[channel] = (prev[channel] + delta) & 0xffff;
    out[i] = prev[channel];
  }
  return out;
}

function dequantizeLonLat(quantized: Uint16Array): Float32Array {
  const out = new Float32Array(quantized.length);
  for (let i = 0; i < quantized.length; i += 2) {
    out[i] = (quantized[i] / 65535) * 360 - 180;
    out[i + 1] = (quantized[i + 1] / 65535) * 180 - 90;
  }
  return out;
}

export async function loadCountryData(): Promise<CountryData> {
  const [manifest, buffer] = await Promise.all([
    fetch("/data/countries.json").then((r) => r.json() as Promise<CountryManifest>),
    fetch("/data/countries.bin").then((r) => r.arrayBuffer()),
  ]);
  if (manifest.version !== FORMAT_VERSION) {
    throw new Error(`Unsupported countries data version ${manifest.version}`);
  }

  const section = ({ byteOffset, length }: Section) => new Uint16Array(buffer, byteOffset, length);

  const fillLonLat = dequantizeLonLat(deltaDecode16(section(manifest.layout.fillLonLat), 2));
  const localIndex = deltaDecode16(section(manifest.layout.fillIndex), 1);
  const borderLonLat = dequantizeLonLat(deltaDecode16(section(manifest.layout.borderLonLat), 2));

  // Expand per-country counts into per-vertex country ids and global indices
  const fillCountry = new Uint16Array(fillLonLat.length / 2);
  const fillIndex = new Uint32Array(localIndex.length);
  const borderCountry = new Uint16Array(borderLonLat.length / 2);
  let vertexOffset = 0;
  let indexOffset = 0;
  let borderOffset = 0;

  manifest.countries.forEach((record, i) => {
    fillCountry.fill(i, vertexOffset, vertexOffset + record.vertexCount);
    for (let k = indexOffset; k < indexOffset + record.indexCount; k++) {
      fillIndex[k] = localIndex[k] + vertexOffset;
    }
    borderCountry.fill(i, borderOffset, borderOffset + record.borderSegments * 2);
    vertexOffset += record.vertexCount;
    indexOffset += record.indexCount;
    borderOffset += record.borderSegments * 2;
  });

  const countries: CountryFeature[] = manifest.countries.map((record, index) => ({
    type: "Feature",
    index,
    properties: record.properties,
    label: { longitude: record.label[0], latitude: record.label[1] },
  }));

  return {
    countries,
    geometry: { fillLonLat, fillCountry, fillIndex, borderLonLat, borderCountry },
  };
}
